[projet]
nom = "nol-csv"
version = "0.1.0"
entree = "src/lib.nol"
auteur = "daliranas <bastien@languedoc.ovh>"
licence = "MIT"
description = "Encodage/decodage CSV (RFC 4180) en pur Nolc."

[dependances]
